package co.bohc.diet.domain.model;

// Generated 2015-4-17 11:55:01 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Code generated by hbm2java
 */
@Entity
@Table(name = "code", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "code_num"))
public class Code implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer codeId;
    private Paper paper;
    private String codeNum;
    private String local;
    private Date creDt;
    private String codeKbn;
    private Date checkDt;
    private Integer checkNum;
    private String person;
    private String delFlg;

    public Code() {
    }

    public Code(Integer codeId, String codeNum, String local, Date creDt) {
        this.codeId = codeId;
        this.codeNum = codeNum;
        this.local = local;
        this.creDt = creDt;
    }

    public Code(Integer codeId, Paper paper, String codeNum, String local, Date creDt, String codeKbn, Date checkDt,
            Integer checkNum, String person, String delFlg) {
        this.codeId = codeId;
        this.paper = paper;
        this.codeNum = codeNum;
        this.local = local;
        this.creDt = creDt;
        this.codeKbn = codeKbn;
        this.checkDt = checkDt;
        this.checkNum = checkNum;
        this.person = person;
        this.delFlg = delFlg;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "code_id", unique = true, nullable = false)
    public Integer getCodeId() {
        return this.codeId;
    }

    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "paper_id")
    public Paper getPaper() {
        return this.paper;
    }

    public void setPaper(Paper paper) {
        this.paper = paper;
    }

    @Column(name = "code_num", unique = true, nullable = false, length = 256)
    public String getCodeNum() {
        return this.codeNum;
    }

    public void setCodeNum(String codeNum) {
        this.codeNum = codeNum;
    }

    @Column(name = "local", nullable = false, length = 256)
    public String getLocal() {
        return this.local;
    }

    public void setLocal(String local) {
        this.local = local;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cre_dt", nullable = false, length = 23)
    public Date getCreDt() {
        return this.creDt;
    }

    public void setCreDt(Date creDt) {
        this.creDt = creDt;
    }

    @Column(name = "code_kbn", length = 2)
    public String getCodeKbn() {
        return this.codeKbn;
    }

    public void setCodeKbn(String codeKbn) {
        this.codeKbn = codeKbn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "check_dt", length = 23)
    public Date getCheckDt() {
        return this.checkDt;
    }

    public void setCheckDt(Date checkDt) {
        this.checkDt = checkDt;
    }

    @Column(name = "check_Num")
    public Integer getCheckNum() {
        return this.checkNum;
    }

    public void setCheckNum(Integer checkNum) {
        this.checkNum = checkNum;
    }

    @Column(name = "person", length = 256)
    public String getPerson() {
        return this.person;
    }

    public void setPerson(String person) {
        this.person = person;
    }

    @Column(name = "del_flg", length = 4)
    public String getDelFlg() {
        return this.delFlg;
    }

    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

}
