package co.bohc.diet.domain.model;
// Generated 2015-2-26 18:28:29 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Code generated by hbm2java
 */
@Entity
@Table(name="code"
    ,schema="dbo"
)
public class Code  implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer codeId;
     private String codeNum;
     private String local;
     private Date creDt;
     private String codeKbn;
     private Date checkDt;

    public Code() {
    }

	
    public Code(Integer codeId, Date creDt) {
        this.codeId = codeId;
        this.creDt = creDt;
    }
    public Code(Integer codeId, String codeNum, String local, Date creDt, String codeKbn, Date checkDt) {
       this.codeId = codeId;
       this.codeNum = codeNum;
       this.local = local;
       this.creDt = creDt;
       this.codeKbn = codeKbn;
       this.checkDt = checkDt;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="code_id", unique=true, nullable=false)
    public Integer getCodeId() {
        return this.codeId;
    }
    
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }
    
    @Column(name="code_num", length=256)
    public String getCodeNum() {
        return this.codeNum;
    }
    
    public void setCodeNum(String codeNum) {
        this.codeNum = codeNum;
    }
    
    @Column(name="local", length=256)
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cre_dt", nullable=false, length=23)
    public Date getCreDt() {
        return this.creDt;
    }
    
    public void setCreDt(Date creDt) {
        this.creDt = creDt;
    }

    @Column(name="code_kbn", length=2, nullable=true)
    public String getCodeKbn() {
        return codeKbn;
    }


    public void setCodeKbn(String codeKbn) {
        this.codeKbn = codeKbn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="check_dt", nullable=false, length=23)
    public Date getCheckDt() {
        return checkDt;
    }


    public void setCheckDt(Date checkDt) {
        this.checkDt = checkDt;
    }

    


}


