package co.bohc.diet.domain.model;

// Generated 2015-4-17 18:10:39 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Paper generated by hbm2java
 */
@Entity
@Table(name = "paper", schema = "dbo", uniqueConstraints = { @UniqueConstraint(columnNames = "paper_code"),
        @UniqueConstraint(columnNames = "report_code") })
public class Paper implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer paperId;
    private String paperCode;
    private String carLicensePlate;
    private String reportCode;
    private Integer printNum;
    private Integer printSize;
    private Date creDt;
    private Date entryDt;
    private Date checkDt;
    private String delFlg;
    private Garage garage;
    private Set<Code> codes = new HashSet<Code>(0);

    public Paper() {
    }

    public Paper(Integer paperId, Integer printNum, Integer printSize) {
        this.paperId = paperId;
        this.printNum = printNum;
        this.printSize = printSize;
    }

    public Paper(Garage garage, Integer paperId, String paperCode, String carLicensePlate, String reportCode, Integer printNum,
            Integer printSize, Date creDt, Date entryDt, Date checkDt, String delFlg, Set<Code> codes) {
        this.paperId = paperId;
        this.paperCode = paperCode;
        this.carLicensePlate = carLicensePlate;
        this.reportCode = reportCode;
        this.printNum = printNum;
        this.printSize = printSize;
        this.creDt = creDt;
        this.entryDt = entryDt;
        this.checkDt = checkDt;
        this.delFlg = delFlg;
        this.codes = codes;
        this.garage = garage;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "paper_id", unique = true, nullable = false)
    public Integer getPaperId() {
        return this.paperId;
    }

    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    @Column(name = "paper_code", unique = true, length = 256)
    public String getPaperCode() {
        return this.paperCode;
    }

    public void setPaperCode(String paperCode) {
        this.paperCode = paperCode;
    }

    @Column(name = "car_license_plate", length = 256)
    public String getCarLicensePlate() {
        return this.carLicensePlate;
    }

    public void setCarLicensePlate(String carLicensePlate) {
        this.carLicensePlate = carLicensePlate;
    }

    @Column(name = "report_code", unique = true, length = 256)
    public String getReportCode() {
        return this.reportCode;
    }

    public void setReportCode(String reportCode) {
        this.reportCode = reportCode;
    }

    @Column(name = "print_num", nullable = false)
    public Integer getPrintNum() {
        return this.printNum;
    }

    public void setPrintNum(Integer printNum) {
        this.printNum = printNum;
    }

    @Column(name = "print_size", nullable = false)
    public Integer getPrintSize() {
        return this.printSize;
    }

    public void setPrintSize(Integer printSize) {
        this.printSize = printSize;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cre_dt", length = 23)
    public Date getCreDt() {
        return this.creDt;
    }

    public void setCreDt(Date creDt) {
        this.creDt = creDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "entry_dt", length = 23)
    public Date getEntryDt() {
        return this.entryDt;
    }

    public void setEntryDt(Date entryDt) {
        this.entryDt = entryDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "check_dt", length = 23)
    public Date getCheckDt() {
        return this.checkDt;
    }

    public void setCheckDt(Date checkDt) {
        this.checkDt = checkDt;
    }

    @Column(name = "del_flg", length = 4)
    public String getDelFlg() {
        return this.delFlg;
    }

    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "paper")
    public Set<Code> getCodes() {
        return this.codes;
    }

    public void setCodes(Set<Code> codes) {
        this.codes = codes;
    }
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "garage_id", nullable = true)
    public Garage getGarage() {
        return this.garage;
    }

    public void setGarage(Garage garage) {
        this.garage = garage;
    }

}
