package co.bohc.diet.domain.model;

// Generated 2015-7-14 14:40:23 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Part generated by hbm2java
 */
@Entity
@Table(name = "part", schema = "dbo")
public class Part implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer partId;
    private String partName;
    private Date creDt;
    private Integer delFlg;
    @JsonIgnore
    private Set<Accessory> accessories = new HashSet<Accessory>(0);

    public Part() {
    }

    public Part(Integer partId, String partName, Date creDt) {
        this.partId = partId;
        this.partName = partName;
        this.creDt = creDt;
    }

    public Part(Integer partId, String partName, Date creDt, Integer delFlg, Set<Accessory> accessories) {
        this.partId = partId;
        this.partName = partName;
        this.creDt = creDt;
        this.delFlg = delFlg;
        this.accessories = accessories;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "part_id", unique = true, nullable = false)
    public Integer getPartId() {
        return this.partId;
    }

    public void setPartId(Integer partId) {
        this.partId = partId;
    }

    @Column(name = "part_name", nullable = false, length = 256)
    public String getPartName() {
        return this.partName;
    }

    public void setPartName(String partName) {
        this.partName = partName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cre_dt", nullable = false, length = 23)
    public Date getCreDt() {
        return this.creDt;
    }

    public void setCreDt(Date creDt) {
        this.creDt = creDt;
    }

    @Column(name = "del_flg")
    public Integer getDelFlg() {
        return this.delFlg;
    }

    public void setDelFlg(Integer delFlg) {
        this.delFlg = delFlg;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "part")
    public Set<Accessory> getAccessories() {
        return this.accessories;
    }

    public void setAccessories(Set<Accessory> accessories) {
        this.accessories = accessories;
    }

}
