package co.bohc.diet.domain.model;
// Generated 2015-9-3 20:30:33 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", schema = "dbo")
public class Status implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer statusId;
	private Integer statusFrom;
	private Integer statusTo;
	private Date creDt;
	private Integer delFlg;
	private String accessoryNum;
	private String worker;

	public Status() {
	}

	public Status(Integer statusId, Integer statusFrom, Integer statusTo, Date creDt, String accessoryNum) {
		this.statusId = statusId;
		this.statusFrom = statusFrom;
		this.statusTo = statusTo;
		this.creDt = creDt;
		this.accessoryNum = accessoryNum;
	}

	public Status(Integer statusId, Integer statusFrom, Integer statusTo, Date creDt, Integer delFlg,
			String accessoryNum, String worker) {
		this.statusId = statusId;
		this.statusFrom = statusFrom;
		this.statusTo = statusTo;
		this.creDt = creDt;
		this.delFlg = delFlg;
		this.accessoryNum = accessoryNum;
		this.worker = worker;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "status_id", unique = true, nullable = false)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status_from", nullable = false)
	public Integer getStatusFrom() {
		return this.statusFrom;
	}

	public void setStatusFrom(Integer statusFrom) {
		this.statusFrom = statusFrom;
	}

	@Column(name = "status_to", nullable = false)
	public Integer getStatusTo() {
		return this.statusTo;
	}

	public void setStatusTo(Integer statusTo) {
		this.statusTo = statusTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cre_dt", nullable = false, length = 23)
	public Date getCreDt() {
		return this.creDt;
	}

	public void setCreDt(Date creDt) {
		this.creDt = creDt;
	}

	@Column(name = "del_flg")
	public Integer getDelFlg() {
		return this.delFlg;
	}

	public void setDelFlg(Integer delFlg) {
		this.delFlg = delFlg;
	}

	@Column(name = "accessory_num", nullable = false, length = 256)
	public String getAccessoryNum() {
		return this.accessoryNum;
	}

	public void setAccessoryNum(String accessoryNum) {
		this.accessoryNum = accessoryNum;
	}

	@Column(name = "worker", length = 256)
	public String getWorker() {
		return this.worker;
	}

	public void setWorker(String worker) {
		this.worker = worker;
	}

}
