package co.bohc.diet.domain.model;

// Generated 2015-4-17 11:55:01 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_user", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class TUser implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer userId;
    private MAdminUser MAdminUser;
    private String password;
    private String email;
    private String firstNameKanji;
    private String lastNameKanji;
    private String firstNameKana;
    private String lastNameKana;
    private Integer sex;
    private String nickName;
    private String birthday;
    private String zip;
    private String prefecture;
    private String address1;
    private String address2;
    private String phoneNumber;
    private String mobileNumber;
    private String paymentResult;
    private String paymentKbn;
    private Date paymentDt;
    private String orderNum;
    private String startRecDate;
    private Double targetWeight;
    private Double firstWeight;
    private Integer targetPoint;
    private String authToken;
    private String userImgPath;
    private Integer backgroundImgNo;
    private Double height;
    private String deviceToken;
    private Integer deviceType;
    private Date creDt;
    private Date updDt;
    private Integer creUserId;
    private Integer updUserId;
    private Integer delFlg;

    public TUser() {
    }

    public TUser(Integer userId, String password, String email, String firstNameKanji, String lastNameKanji,
            String firstNameKana, String lastNameKana, Integer sex, String nickName, String birthday, String zip,
            String prefecture, String address1, String address2, String phoneNumber, Integer backgroundImgNo,
            Integer deviceType, Date creDt, Date updDt, Integer creUserId, Integer updUserId, Integer delFlg) {
        this.userId = userId;
        this.password = password;
        this.email = email;
        this.firstNameKanji = firstNameKanji;
        this.lastNameKanji = lastNameKanji;
        this.firstNameKana = firstNameKana;
        this.lastNameKana = lastNameKana;
        this.sex = sex;
        this.nickName = nickName;
        this.birthday = birthday;
        this.zip = zip;
        this.prefecture = prefecture;
        this.address1 = address1;
        this.address2 = address2;
        this.phoneNumber = phoneNumber;
        this.backgroundImgNo = backgroundImgNo;
        this.deviceType = deviceType;
        this.creDt = creDt;
        this.updDt = updDt;
        this.creUserId = creUserId;
        this.updUserId = updUserId;
        this.delFlg = delFlg;
    }

    public TUser(Integer userId, MAdminUser MAdminUser, String password, String email, String firstNameKanji,
            String lastNameKanji, String firstNameKana, String lastNameKana, Integer sex, String nickName,
            String birthday, String zip, String prefecture, String address1, String address2, String phoneNumber,
            String mobileNumber, String paymentResult, String paymentKbn, Date paymentDt, String orderNum,
            String startRecDate, Double targetWeight, Double firstWeight, Integer targetPoint, String authToken,
            String userImgPath, Integer backgroundImgNo, Double height, String deviceToken, Integer deviceType,
            Date creDt, Date updDt, Integer creUserId, Integer updUserId, Integer delFlg) {
        this.userId = userId;
        this.MAdminUser = MAdminUser;
        this.password = password;
        this.email = email;
        this.firstNameKanji = firstNameKanji;
        this.lastNameKanji = lastNameKanji;
        this.firstNameKana = firstNameKana;
        this.lastNameKana = lastNameKana;
        this.sex = sex;
        this.nickName = nickName;
        this.birthday = birthday;
        this.zip = zip;
        this.prefecture = prefecture;
        this.address1 = address1;
        this.address2 = address2;
        this.phoneNumber = phoneNumber;
        this.mobileNumber = mobileNumber;
        this.paymentResult = paymentResult;
        this.paymentKbn = paymentKbn;
        this.paymentDt = paymentDt;
        this.orderNum = orderNum;
        this.startRecDate = startRecDate;
        this.targetWeight = targetWeight;
        this.firstWeight = firstWeight;
        this.targetPoint = targetPoint;
        this.authToken = authToken;
        this.userImgPath = userImgPath;
        this.backgroundImgNo = backgroundImgNo;
        this.height = height;
        this.deviceToken = deviceToken;
        this.deviceType = deviceType;
        this.creDt = creDt;
        this.updDt = updDt;
        this.creUserId = creUserId;
        this.updUserId = updUserId;
        this.delFlg = delFlg;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id", unique = true, nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admin_user_id")
    public MAdminUser getMAdminUser() {
        return this.MAdminUser;
    }

    public void setMAdminUser(MAdminUser MAdminUser) {
        this.MAdminUser = MAdminUser;
    }

    @Column(name = "password", nullable = false, length = 256)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "email", unique = true, nullable = false, length = 128)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "first_name_kanji", nullable = false, length = 30)
    public String getFirstNameKanji() {
        return this.firstNameKanji;
    }

    public void setFirstNameKanji(String firstNameKanji) {
        this.firstNameKanji = firstNameKanji;
    }

    @Column(name = "last_name_kanji", nullable = false, length = 30)
    public String getLastNameKanji() {
        return this.lastNameKanji;
    }

    public void setLastNameKanji(String lastNameKanji) {
        this.lastNameKanji = lastNameKanji;
    }

    @Column(name = "first_name_kana", nullable = false, length = 30)
    public String getFirstNameKana() {
        return this.firstNameKana;
    }

    public void setFirstNameKana(String firstNameKana) {
        this.firstNameKana = firstNameKana;
    }

    @Column(name = "last_name_kana", nullable = false, length = 30)
    public String getLastNameKana() {
        return this.lastNameKana;
    }

    public void setLastNameKana(String lastNameKana) {
        this.lastNameKana = lastNameKana;
    }

    @Column(name = "sex", nullable = false)
    public Integer getSex() {
        return this.sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    @Column(name = "nick_name", nullable = false, length = 30)
    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    @Column(name = "birthday", nullable = false, length = 10)
    public String getBirthday() {
        return this.birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    @Column(name = "zip", nullable = false, length = 7)
    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    @Column(name = "prefecture", nullable = false, length = 5)
    public String getPrefecture() {
        return this.prefecture;
    }

    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }

    @Column(name = "address1", nullable = false, length = 25)
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name = "address2", nullable = false, length = 70)
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name = "phone_number", nullable = false, length = 13)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "mobile_number", length = 13)
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    @Column(name = "payment_result")
    public String getPaymentResult() {
        return this.paymentResult;
    }

    public void setPaymentResult(String paymentResult) {
        this.paymentResult = paymentResult;
    }

    @Column(name = "payment_kbn", length = 2)
    public String getPaymentKbn() {
        return this.paymentKbn;
    }

    public void setPaymentKbn(String paymentKbn) {
        this.paymentKbn = paymentKbn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "payment_dt", length = 23)
    public Date getPaymentDt() {
        return this.paymentDt;
    }

    public void setPaymentDt(Date paymentDt) {
        this.paymentDt = paymentDt;
    }

    @Column(name = "order_num", length = 80)
    public String getOrderNum() {
        return this.orderNum;
    }

    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    @Column(name = "start_rec_date", length = 10)
    public String getStartRecDate() {
        return this.startRecDate;
    }

    public void setStartRecDate(String startRecDate) {
        this.startRecDate = startRecDate;
    }

    @Column(name = "target_weight", precision = 4, scale = 1)
    public Double getTargetWeight() {
        return this.targetWeight;
    }

    public void setTargetWeight(Double targetWeight) {
        this.targetWeight = targetWeight;
    }

    @Column(name = "first_weight", precision = 4, scale = 1)
    public Double getFirstWeight() {
        return this.firstWeight;
    }

    public void setFirstWeight(Double firstWeight) {
        this.firstWeight = firstWeight;
    }

    @Column(name = "target_point")
    public Integer getTargetPoint() {
        return this.targetPoint;
    }

    public void setTargetPoint(Integer targetPoint) {
        this.targetPoint = targetPoint;
    }

    @Column(name = "auth_token", length = 256)
    public String getAuthToken() {
        return this.authToken;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    @Column(name = "user_img_path", length = 256)
    public String getUserImgPath() {
        return this.userImgPath;
    }

    public void setUserImgPath(String userImgPath) {
        this.userImgPath = userImgPath;
    }

    @Column(name = "background_img_no", nullable = false)
    public Integer getBackgroundImgNo() {
        return this.backgroundImgNo;
    }

    public void setBackgroundImgNo(Integer backgroundImgNo) {
        this.backgroundImgNo = backgroundImgNo;
    }

    @Column(name = "height", precision = 4, scale = 1)
    public Double getHeight() {
        return this.height;
    }

    public void setHeight(Double height) {
        this.height = height;
    }

    @Column(name = "device_token", length = 256)
    public String getDeviceToken() {
        return this.deviceToken;
    }

    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }

    @Column(name = "device_type", nullable = false)
    public Integer getDeviceType() {
        return this.deviceType;
    }

    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cre_dt", nullable = false, length = 23)
    public Date getCreDt() {
        return this.creDt;
    }

    public void setCreDt(Date creDt) {
        this.creDt = creDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "upd_dt", nullable = false, length = 23)
    public Date getUpdDt() {
        return this.updDt;
    }

    public void setUpdDt(Date updDt) {
        this.updDt = updDt;
    }

    @Column(name = "cre_user_id", nullable = false)
    public Integer getCreUserId() {
        return this.creUserId;
    }

    public void setCreUserId(Integer creUserId) {
        this.creUserId = creUserId;
    }

    @Column(name = "upd_user_id", nullable = false)
    public Integer getUpdUserId() {
        return this.updUserId;
    }

    public void setUpdUserId(Integer updUserId) {
        this.updUserId = updUserId;
    }

    @Column(name = "del_flg", nullable = false)
    public Integer getDelFlg() {
        return this.delFlg;
    }

    public void setDelFlg(Integer delFlg) {
        this.delFlg = delFlg;
    }

}
