package co.bohc.diet.domain.model;

// Generated 2015-4-17 18:10:39 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Worker generated by hbm2java
 */
@Entity
@Table(name = "worker", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "worker_name"))
public class Worker implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer workerId;
    private String workerName;
    private String local;
    private Date creDt;
    private String delFlg;
    private Set<Code> codes = new HashSet<Code>(0);

    public Worker() {
    }

    public Worker(Integer workerId, String workerName, String local, Date creDt) {
        this.workerId = workerId;
        this.workerName = workerName;
        this.local = local;
        this.creDt = creDt;
    }

    public Worker(Integer workerId, String workerName, String local, Date creDt, String delFlg, Set<Code> codes) {
        this.workerId = workerId;
        this.workerName = workerName;
        this.local = local;
        this.creDt = creDt;
        this.delFlg = delFlg;
        this.codes = codes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "worker_id", unique = true, nullable = false)
    public Integer getWorkerId() {
        return this.workerId;
    }

    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    @Column(name = "worker_name", unique = true, nullable = false, length = 256)
    public String getWorkerName() {
        return this.workerName;
    }

    public void setWorkerName(String workerName) {
        this.workerName = workerName;
    }

    @Column(name = "local", nullable = false, length = 256)
    public String getLocal() {
        return this.local;
    }

    public void setLocal(String local) {
        this.local = local;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cre_dt", nullable = false, length = 23)
    public Date getCreDt() {
        return this.creDt;
    }

    public void setCreDt(Date creDt) {
        this.creDt = creDt;
    }

    @Column(name = "del_flg", length = 4)
    public String getDelFlg() {
        return this.delFlg;
    }

    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "worker")
    public Set<Code> getCodes() {
        return this.codes;
    }

    public void setCodes(Set<Code> codes) {
        this.codes = codes;
    }

}
